name: Check terraform files code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow-in-another-repo:
   uses: msandhyarani/tflint-ga/.github/workflows/terraform-lint.yml@main
   with:
      config_file: './build-support/terraform/.tflint.hcl'
      workflow_id: terraform-lint.yml
      files_to_match: \.(tf|tfvars)$
      os: "ubuntu-latest"
   secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      gh_repo_read_token: ${{ secrets.GH_REPO_READ_TOKEN }}
